# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mjx/internal/mjx.proto for package 'mjxproto'

require 'grpc'
require 'mjx/internal/mjx_pb'

module Mjxproto
  module Agent
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mjxproto.Agent'

      rpc :TakeAction, ::Mjxproto::Observation, ::Mjxproto::Action
    end

    Stub = Service.rpc_stub_class
  end
end
